services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: drizzle_owner
      POSTGRES_PASSWORD: p4ZzY7WXUGdO
      POSTGRES_DB: drizzle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U drizzle_owner -d drizzle" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://drizzle_owner:p4ZzY7WXUGdO@postgres:5432/drizzle
      - PORT=5000
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - server

volumes:
  postgres_data:
